# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pymoq',
                'doc_host': 'https://omlnaut.github.io',
                'git_url': 'https://github.com/omlnaut/pymoq',
                'lib_path': 'pymoq'},
  'syms': {'pymoq.core': {'pymoq.core.foo': ('core.html#foo', 'pymoq/core.py')}}}