# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_validators.ipynb.

# %% auto 0
__all__ = ['AnyArg', 'ArgumentValidator', 'ArgumentFunctionValidator', 'argument_validator_from_argument']

# %% ../nbs/01_validators.ipynb 2
from typing import Protocol, Any, runtime_checkable
from collections.abc import Callable
from .core import AnyCallable

# %% ../nbs/01_validators.ipynb 8
@runtime_checkable
class ArgumentValidator(Protocol):
    "Interface for all argument validators."
    
    @property
    def name() -> str:
        "Name of the argument in the signature"
        
    @property
    def position() -> int:
        "Position of the argument in the signature"
        
    def is_valid(self, argument: Any) -> bool:
        ...

# %% ../nbs/01_validators.ipynb 10
class ArgumentFunctionValidator:
    "Validate an argument by evaluating an arbitrary function"
    def __init__(self, func: AnyCallable[bool], name: str, position: int):
        self._func = func
        self._name = name
        self._position = position
        
    @property
    def name(self) -> str:
        return self._name
    
    @property
    def position(self) -> int:
        return self._position
        
    def is_valid(self, argument: Any) -> bool:
        return self._func(argument)
    
    def __str__(self): return f'ArgumentFunctionValidator({self.name}, {self.position})'
    def __repr__(self): return str(self)
    
assert isinstance(ArgumentFunctionValidator, ArgumentValidator), "ArgumentFunctionValidator does not implement the ArgumentValidator-Protocol"

# %% ../nbs/01_validators.ipynb 16
def argument_validator_from_argument(argument: Any, name:str, position: int) -> ArgumentValidator:
    match argument:
        case ArgumentValidator():
            return argument
        case type():
            return ArgumentFunctionValidator(lambda v: isinstance(v, argument), name=name, position=position)
        case Callable():
            return ArgumentFunctionValidator(argument, name=name, position=position)
    
    return ArgumentFunctionValidator(lambda v: v==argument, name=name, position=position)

# %% ../nbs/01_validators.ipynb 29
AnyArg = lambda: lambda v: True
