# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hy']

# %% ../nbs/00_core.ipynb 3
def foo(): return 'bar'

# %% ../nbs/00_core.ipynb 5
def say_hy(to: str) -> str:
    return f'hy {to}!'
