# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/implementation/00_core.ipynb.

# %% auto 0
__all__ = ['T', 'AnyCallable']

# %% ../nbs/implementation/00_core.ipynb 1
from typing import Protocol, Generic, TypeVar

# %% ../nbs/implementation/00_core.ipynb 4
T = TypeVar('T')
class AnyCallable(Generic[T], Protocol):
    "Generic interface for an object with a call operator that takes any number of arguments (both positional and named) and returns the type T"
    def __call__(self, *args, **kwargs) -> T:
        ...
