# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_return_value_generators.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_return_value_generators.ipynb 1
from .argument_validators import ArgumentValidator, ArgumentFunctionValidator
from typing import Any

# %% ../nbs/03_return_value_generators.ipynb 2
from fastcore.test import test_fail
