# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_Verfiy.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/06_Verfiy.ipynb 2
from dataclasses import dataclass
from typing import Any

from .mocking.functions import FunctionMock
