project:
  type: website
  preview:
    port: 3000
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
    - auto: "/*.ipynb"
    - index.ipynb

  navbar:
    background: primary
    search: true
    left:
     - text: "Implementation"
       href: implementation/00_core.ipynb
     - text: "Documentation"
       href: doc/general.ipynb
metadata-files: [nbdev.yml, sidebar.yml]