# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_mocking_objects.ipynb.

# %% auto 0
__all__ = ['get_public_names']

# %% ../../nbs/05_mocking_objects.ipynb 11
def _is_public_name(name: str):
    "Returns whether or not a (member) name is public"
    return not name.startswith('_')

def get_public_names(protocol: type) -> list[str]:
    "Returns all names that are considered public from the given"
    names = [name for name in dir(protocol) if _is_public_name(name)]
    return names
